package com.pentagon.empDate;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

public class EmployeeData {

public static void main(String[] args) {
	Connection com=null;
	String url="jdbc:mysql://localhost:3306/company";
	String user="root";
	String password="tiger";
	Statement stmt=null;
	int id=0;
	ResultSet rs=null;
	Scanner sc = new Scanner(System.in);
	
	try
	{
		//Loading and Regestering the driver class
		Class.forName("com.mysql.cj.jdbc.Driver");
		
		
		
		System.out.println("Drivers loaded and registered successfully");
		
		
		//establishing connection
		com=DriverManager.getConnection(url,user,password);
		System.out.println("Connection established successfully");
		//Creating a platform
		stmt=com.createStatement();
		/*create statement() is a helper method present in connection interface
		 * which is used to create reference of type statement interface
		 */
		System.out.println("platform created");
		
		System.out.println("Enter your id:");
		id = sc.nextInt();
		//Executing SQL queries
		rs=stmt.executeQuery("select* from emp where eid="+id+"");
		/*resultset interface is used to carry the resultant data of DQL query
		 * from curser or buffer memory. once the query is executed executequery()
		 * creates and returns the reference object of type resultset. Now rs holds
		 * the resultant data generated by execution of query
		 */
		
		if(rs.next())
		{
			int eid=rs.getInt(1);
			String fname=rs.getString(2);
			String job=rs.getString(6);
			Double sal=rs.getDouble(9);
			System.out.println("Employee ID :"+eid);
			System.out.println("Employee name :"+fname);
			System.out.println("job role :"+job );
			System.out.println("sallary :"+ sal);
			
		}
		
		
	}
	
	catch(ClassNotFoundException | SQLException e) {
		
		e.printStackTrace();
		
	
	}
}
}
